# Generated by Django 5.2.7 on 2025-10-02 08:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivejob',
            options={'ordering': ['-started_at'], 'verbose_name': 'Archive Job', 'verbose_name_plural': 'Archive Jobs'},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Email Verification', 'verbose_name_plural': 'Email Verifications'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='s3config',
            options={'verbose_name': 'S3 Configuration', 'verbose_name_plural': 'S3 Configurations'},
        ),
        migrations.AlterModelOptions(
            name='uploadjob',
            options={'ordering': ['-started_at'], 'verbose_name': 'Upload Job', 'verbose_name_plural': 'Upload Jobs'},
        ),
        migrations.AddField(
            model_name='archivejob',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Token expiration time'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='checksum',
            field=models.CharField(blank=True, help_text='File checksum for integrity', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='total_size',
            field=models.BigIntegerField(default=0, help_text='Total size of all files in bytes'),
        ),
        migrations.AlterField(
            model_name='archivejob',
            name='job_type',
            field=models.CharField(choices=[('archive', 'Archive'), ('restore', 'Restore')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='archivejob',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='archivejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='s3_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('archiving', 'Archiving'), ('archived', 'Archived'), ('restoring', 'Restoring'), ('restored', 'Restored'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='s3config',
            name='bucket_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='job_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='archivejob',
            index=models.Index(fields=['user', 'status'], name='api_archive_user_id_620491_idx'),
        ),
        migrations.AddIndex(
            model_name='archivejob',
            index=models.Index(fields=['user', 'job_type'], name='api_archive_user_id_0d5446_idx'),
        ),
        migrations.AddIndex(
            model_name='archivejob',
            index=models.Index(fields=['status', 'started_at'], name='api_archive_status_c3447f_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', 'status'], name='api_mediafi_user_id_d20c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', 'uploaded_at'], name='api_mediafi_user_id_f31af2_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'status'], name='api_mediafi_file_ty_731818_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['user', 'status'], name='api_uploadj_user_id_c57952_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['status', 'started_at'], name='api_uploadj_status_99dc22_idx'),
        ),
    ]
