# Generated by Django 5.2.7 on 2025-10-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_archivejob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivejob',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, help_text='Estimated completion time for restore', null=True),
        ),
        migrations.AddField(
            model_name='archivejob',
            name='glacier_job_id',
            field=models.CharField(blank=True, help_text='Glacier job ID for restore operations', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='glacier_archive_id',
            field=models.CharField(blank=True, help_text='Glacier archive ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='restore_tier',
            field=models.CharField(choices=[('Expedited', 'Expedited (1-5 min)'), ('Standard', 'Standard (3-5 hours)'), ('Bulk', 'Bulk (5-12 hours)')], default='Standard', help_text='Glacier restore tier', max_length=20),
        ),
    ]
