# Generated by Django 5.2.7 on 2025-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_archivejob_estimated_completion_and_more'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='uploadjob',
            name='directory_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Directory structure metadata'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='rollback_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data needed for rollback operations'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list, help_text='List of successfully uploaded files'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='failed_files_count',
            field=models.IntegerField(default=0, help_text='Number of failed files'),
        ),
        # Remove the old failed_files field and add new one
        migrations.RemoveField(
            model_name='uploadjob',
            name='failed_files',
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='failed_files',
            field=models.JSONField(blank=True, default=list, help_text='List of failed files with errors'),
        ),
    ]
