# Generated by Django 5.2.7 on 2025-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadjob_directory_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the file was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
