# Generated by Django 5.2.7 on 2025-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mediafile_deleted_at_mediafile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='relative_path',
            field=models.CharField(blank=True, db_index=True, help_text='Relative path of the file within the folder structure', max_length=1000, null=True),
        ),
    ]
