# Generated by Django 5.2.7 on 2025-10-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mediafile_relative_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='encryption_metadata',
            field=models.JSONField(blank=True, help_text='Encryption metadata including algorithm, IV, key info', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the file is encrypted'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time the file was accessed', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='storage_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Storage cost in USD', max_digits=10, null=True),
        ),
    ]
