# Generated by Django 5.2.7 on 2025-10-06 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mediafile_encryption_metadata_mediafile_is_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', 'relative_path', 'is_deleted'], name='api_mediafi_user_id_0ac3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', 'is_deleted', 'uploaded_at'], name='api_mediafi_user_id_03727a_idx'),
        ),
    ]
