# Generated by Django 5.2.7 on 2025-10-11 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HibernationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('deep_freeze', '🌙 Hibernate (Deep Freeze Tier)'), ('flexible_archive', '🌤️ Smart Hibernate (Flexible Archive Tier)'), ('instant_archive', '⚡ Quick Hibernate (Instant Archive Tier)')], max_length=100, unique=True)),
                ('storage_tier', models.CharField(choices=[('100gb', '100 GB'), ('500gb', '500 GB'), ('1tb', '1 TB')], max_length=20)),
                ('aws_storage_type', models.CharField(help_text='AWS storage type (deep_archive, glacier_flexible, glacier_instant)', max_length=50)),
                ('restore_time_hours', models.IntegerField(help_text='Restore time in hours')),
                ('user_cost_inr', models.DecimalField(decimal_places=2, help_text='User cost in INR per month', max_digits=10)),
                ('annual_price_inr', models.DecimalField(decimal_places=2, help_text='Annual price in INR', max_digits=10)),
                ('margin_inr', models.DecimalField(decimal_places=2, help_text='Margin in INR', max_digits=10)),
                ('free_retrieval_gb', models.IntegerField(default=0, help_text='Free retrieval GB per period')),
                ('retrieval_period_months', models.IntegerField(default=6, help_text='Retrieval period in months')),
                ('additional_retrieval_cost_per_gb', models.DecimalField(decimal_places=2, help_text='Additional retrieval cost per GB in INR', max_digits=10)),
                ('user_message', models.TextField(help_text='User-facing message about the plan')),
                ('description', models.TextField(help_text='Plan description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hibernation Plan',
                'verbose_name_plural': 'Hibernation Plans',
                'unique_together': {('name', 'storage_tier')},
            },
        ),
        migrations.CreateModel(
            name='UserHibernationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Plan expiration date')),
                ('is_active', models.BooleanField(default=True)),
                ('storage_used_bytes', models.BigIntegerField(default=0, help_text='Storage used in bytes')),
                ('retrieval_used_gb', models.DecimalField(decimal_places=2, default=0, help_text='Retrieval used in GB this period', max_digits=10)),
                ('retrieval_period_start', models.DateTimeField(auto_now_add=True, help_text='Start of current retrieval period')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hibernationplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hibernation_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hibernation Plan',
                'verbose_name_plural': 'User Hibernation Plans',
            },
        ),
        migrations.DeleteModel(
            name='UploadJob',
        ),
    ]
