# Generated by Django 5.2.7 on 2025-10-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hibernationplan_userhibernationplan_delete_uploadjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hibernationplan',
            name='name',
            field=models.CharField(choices=[('deep_freeze', '🌙 Hibernate (Deep Freeze Tier)'), ('flexible_archive', '🌤️ Smart Hibernate (Flexible Archive Tier)'), ('instant_archive', '⚡ Quick Hibernate (Instant Archive Tier)')], max_length=100),
        ),
    ]
