# Generated by Django 5.2.7 on 2025-10-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_hibernationplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hibernationplan',
            name='additional_retrieval_cost_per_gb',
        ),
    ]
