# Generated by Django 5.2.7 on 2025-10-11 05:07

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HibernationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name (e.g., deep_freeze, smart_hibernate)', max_length=100)),
                ('storage_tier', models.CharField(help_text='Storage tier (100gb, 500gb, 1tb)', max_length=20)),
                ('description', models.TextField(default='', help_text='Plan description')),
                ('monthly_price_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in INR', max_digits=10)),
                ('annual_price_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual price in INR', max_digits=10)),
                ('storage_limit_gb', models.IntegerField(default=100, help_text='Storage limit in GB')),
                ('aws_storage_class', models.CharField(default='DEEP_ARCHIVE', help_text='AWS storage class (DEEP_ARCHIVE, GLACIER, STANDARD)', max_length=50)),
                ('restore_time_hours', models.IntegerField(default=12, help_text='Restore time in hours')),
                ('retrieval_policy', models.TextField(default='', help_text='Retrieval policy description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hibernation Plan',
                'verbose_name_plural': 'Hibernation Plans',
            },
        ),
        migrations.CreateModel(
            name='UserHibernationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=timezone.now, help_text='Subscription expiration date')),
                ('auto_renew', models.BooleanField(default=True, help_text='Whether to auto-renew subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='api.hibernationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hibernation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hibernation Plan',
                'verbose_name_plural': 'User Hibernation Plans',
            },
        ),
        migrations.AddConstraint(
            model_name='hibernationplan',
            constraint=models.UniqueConstraint(fields=('name', 'storage_tier'), name='api_hibernationplan_name_storage_tier_unique'),
        ),
    ]
