# Generated by Django 5.2.7 on 2025-10-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_hibernation_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveConstraint(
            model_name='hibernationplan',
            name='api_hibernationplan_name_storage_tier_unique',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_inr',
            field=models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hibernation_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.hibernationplan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(help_text='Razorpay order ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay signature', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_hibernation_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.userhibernationplan'),
        ),
        migrations.AlterUniqueTogether(
            name='hibernationplan',
            unique_together={('name', 'storage_tier')},
        ),
    ]
