# Generated by Django 5.2.7 on 2025-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_missing_hibernation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hibernationplan',
            name='monthly_price_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='storage_limit_gb',
            field=models.IntegerField(default=100, help_text='Storage limit in GB'),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='aws_storage_class',
            field=models.CharField(default='DEEP_ARCHIVE', help_text='AWS storage class (DEEP_ARCHIVE, GLACIER, STANDARD)', max_length=50),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='retrieval_policy',
            field=models.TextField(default='', help_text='Retrieval policy description'),
        ),
    ]
