# Generated by Django 5.2.7 on 2025-10-11 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_migrate_encrypt_existing_secret_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='userhibernationplan',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='userhibernationplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userhibernationplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='aws_storage_type',
            field=models.CharField(default='deep_archive', help_text='AWS storage type', max_length=50),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='free_retrieval_gb',
            field=models.IntegerField(default=10, help_text='Free retrieval in GB'),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='margin_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Margin in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='retrieval_period_months',
            field=models.IntegerField(default=6, help_text='Retrieval period in months'),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='user_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='User cost in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='hibernationplan',
            name='user_message',
            field=models.TextField(default='', help_text='User message'),
        ),
        migrations.AddField(
            model_name='userhibernationplan',
            name='retrieval_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start of retrieval period'),
        ),
        migrations.AddField(
            model_name='userhibernationplan',
            name='retrieval_used_gb',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Retrieval used in GB', max_digits=10),
        ),
        migrations.AddField(
            model_name='userhibernationplan',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text='Storage used in bytes'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(help_text='Token expiration time'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('card', 'Card')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
