# Generated by Django 5.2.7 on 2025-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fix_email_verification_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhibernationplan',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Whether to automatically renew this subscription'),
        ),
    ]
