# Generated by Django 5.2.7 on 2025-10-12 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLifetimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_uploaded_bytes', models.BigIntegerField(default=0, help_text='Total bytes uploaded')),
                ('total_downloaded_bytes', models.BigIntegerField(default=0, help_text='Total bytes downloaded')),
                ('total_deleted_bytes', models.BigIntegerField(default=0, help_text='Total bytes deleted')),
                ('peak_storage_bytes', models.BigIntegerField(default=0, help_text='Peak storage usage in bytes')),
                ('files_uploaded_count', models.IntegerField(default=0, help_text='Total files uploaded')),
                ('files_downloaded_count', models.IntegerField(default=0, help_text='Total files downloaded')),
                ('files_deleted_count', models.IntegerField(default=0, help_text='Total files deleted')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('upload_delete_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Upload/delete ratio', max_digits=5)),
                ('rapid_cycles_count', models.IntegerField(default=0, help_text='Count of rapid upload/delete cycles')),
                ('abuse_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Abuse score (0-1)', max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lifetime Usage',
                'verbose_name_plural': 'User Lifetime Usages',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('restore', 'Restore'), ('archive', 'Archive')], db_index=True, max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='User IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('month', models.DateField(db_index=True, help_text='Month for tracking (first day of month)')),
                ('daily_uploads', models.IntegerField(default=0, help_text='Daily upload count')),
                ('daily_downloads', models.IntegerField(default=0, help_text='Daily download count')),
                ('daily_storage_changes', models.BigIntegerField(default=0, help_text='Daily storage changes in bytes')),
                ('file_id', models.IntegerField(blank=True, help_text='MediaFile ID if applicable', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the activity was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='api_useract_user_id_937f3e_idx'), models.Index(fields=['user', 'month'], name='api_useract_user_id_6db6ab_idx'), models.Index(fields=['activity_type', 'timestamp'], name='api_useract_activit_dc27ac_idx'), models.Index(fields=['user', 'activity_type', 'month'], name='api_useract_user_id_a659a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='First day of the month')),
                ('upload_limit_bytes', models.BigIntegerField(default=16106127360, help_text='Monthly upload limit in bytes (15GB)')),
                ('download_limit_bytes', models.BigIntegerField(default=53687091200, help_text='Monthly download limit in bytes (50GB)')),
                ('storage_limit_bytes', models.BigIntegerField(default=16106127360, help_text='Monthly storage limit in bytes (15GB)')),
                ('uploads_used_bytes', models.BigIntegerField(default=0, help_text='Bytes uploaded this month')),
                ('downloads_used_bytes', models.BigIntegerField(default=0, help_text='Bytes downloaded this month')),
                ('storage_peak_bytes', models.BigIntegerField(default=0, help_text='Peak storage usage this month')),
                ('current_storage_bytes', models.BigIntegerField(default=0, help_text='Current storage usage')),
                ('upload_count', models.IntegerField(default=0, help_text='Number of uploads this month')),
                ('download_count', models.IntegerField(default=0, help_text='Number of downloads this month')),
                ('delete_count', models.IntegerField(default=0, help_text='Number of deletions this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Monthly Limits',
                'verbose_name_plural': 'User Monthly Limits',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', 'month'], name='api_usermon_user_id_b45682_idx'), models.Index(fields=['month'], name='api_usermon_month_d18db1_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
