# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userhibernationplan_auto_renew'),
        ('api', '0022_userlifetimeusage_useractivity_usermonthlylimits'),
    ]

    operations = [
    ]
