# Generated by Django 5.2.7 on 2025-10-15 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('uploaded_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('root_directory', models.CharField(blank=True, max_length=500)),
                ('directory_structure', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uppy_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('relative_path', models.CharField(blank=True, help_text='Relative path within the uploaded directory', max_length=1000)),
                ('parent_directory', models.CharField(blank=True, help_text='Parent directory name', max_length=500)),
                ('upload_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000)),
                ('s3_etag', models.CharField(blank=True, max_length=100)),
                ('encryption_metadata', models.JSONField(blank=True, help_text='Encryption metadata including algorithm, IV, key info', null=True)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether the file is encrypted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uppy_files', to=settings.AUTH_USER_MODEL)),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='uppy_upload.uploadsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'status'], name='uppy_upload_user_id_f675d7_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['session_id'], name='uppy_upload_session_1d1a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'uploaded_at'], name='uppy_upload_user_id_67175c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'parent_directory'], name='uppy_upload_user_id_9e0506_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['upload_id'], name='uppy_upload_upload__5c7f44_idx'),
        ),
    ]
