# Generated by Django 5.2.7 on 2025-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uppy_upload', '0002_uploadedfile_upload_session'),
    ]

    operations = [
        # Add encryption_metadata field (nullable)
        migrations.AddField(
            model_name='uploadedfile',
            name='encryption_metadata',
            field=models.JSONField(blank=True, help_text='Encryption metadata including algorithm, IV, key info', null=True),
        ),
        # Add is_encrypted field (nullable first)
        migrations.AddField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the file is encrypted', null=True),
        ),
        # Update existing records to set is_encrypted = False
        migrations.RunSQL(
            "UPDATE uppy_upload_uploadedfile SET is_encrypted = false WHERE is_encrypted IS NULL;",
            reverse_sql="UPDATE uppy_upload_uploadedfile SET is_encrypted = NULL WHERE is_encrypted = false;"
        ),
        # Make is_encrypted NOT NULL
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the file is encrypted'),
        ),
    ]
