# Generated by Django 5.2.7 on 2025-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uppy_upload', '0002_uploadedfile_upload_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='encryption_metadata',
            field=models.JSONField(blank=True, help_text='Encryption metadata including algorithm, IV, key info', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the file is encrypted'),
        ),
    ]
